import "C:\Programme\Microsoft Visual Studio 8\VC\PlatformSDK\include\prsht.idl";
import "C:\Programme\Microsoft Visual Studio 8\VC\PlatformSDK\include\mshtml.idl";
import "c:\programme\microsoft visual studio 8\vc\platformsdk\include\dimm.idl";
import "C:\Programme\Microsoft Visual Studio 8\VC\PlatformSDK\include\mshtmhst.idl";
import "c:\programme\microsoft visual studio 8\vc\platformsdk\include\docobj.idl";
import "C:\Programme\Microsoft Visual Studio 8\VC\PlatformSDK\include\exdisp.idl";
import "C:\Programme\Microsoft Visual Studio 8\VC\PlatformSDK\include\objsafe.idl";

#line 14 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface IVector3D;
#line 19 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface _IKeyboardEvents;
#line 22 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface ISimpleDevice;
#line 24 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface ITDxInfo;
#line 28 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface _ISensorEvents;
#line 31 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface ISensor;
#line 34 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface IAngleAxis;
#line 38 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface IKeyboard;
#line 41 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __ISimpleDeviceEvents_DeviceChangeEventHandler;
#line 43 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __IKeyboardEvents_KeyDownEventHandler;
#line 45 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __IKeyboardEvents_KeyUpEventHandler;
#line 47 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __ISensorEvents_SensorInputEventHandler;
#line 49 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface _func;
[
	uuid(8c2aa71d-2b23-43f5-a6ed-4df57e9cd8d5),
	dual
] 
#line 95 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface IVector3D : IDispatch {
#line 101 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(1)] HRESULT  X([out,retval] double *pRetVal);
#line 103 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(1)] HRESULT  X([in] double pRetVal);
#line 105 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(2)] HRESULT  Y([out,retval] double *pRetVal);
#line 107 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(2)] HRESULT  Y([in] double pRetVal);
#line 109 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(3)] HRESULT  Z([out,retval] double *pRetVal);
#line 111 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(3)] HRESULT  Z([in] double pRetVal);
#line 113 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(4)] HRESULT  Length([out,retval] double *pRetVal);
#line 115 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(4)] HRESULT  Length([in] double pRetVal);
};

[
	uuid(e9d6b6c3-117c-340f-9dd3-fc3e9f84c58f)
] 
#line 156 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
enum functions {
	functions_none = 0,
	functions_sin = 1,
	functions_square = 2,
	functions_cube = 3,
};

[
	uuid(00612962-8fb6-47b2-bf98-4e8c0ff5f559),
	dual
] 
#line 164 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface ITDxInfo : IDispatch {
#line 170 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[id(1)] HRESULT  RevisionNumber([out,retval] BSTR *pRetVal);
};

[
	uuid(1ef2baff-54e9-4706-9f61-078f7134fd35),
	dual
] 
#line 214 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface IAngleAxis : IDispatch {
#line 220 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(1)] HRESULT  X([out,retval] double *pRetVal);
#line 222 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(1)] HRESULT  X([in] double pRetVal);
#line 224 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(2)] HRESULT  Y([out,retval] double *pRetVal);
#line 226 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(2)] HRESULT  Y([in] double pRetVal);
#line 228 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(3)] HRESULT  Z([out,retval] double *pRetVal);
#line 230 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(3)] HRESULT  Z([in] double pRetVal);
#line 232 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(4)] HRESULT  Angle([out,retval] double *pRetVal);
#line 234 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propput,id(4)] HRESULT  Angle([in] double pRetVal);
};

[
	uuid(f3a6775e-6fa1-4829-bf32-5b045c29078f),
	dual
] 
#line 239 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface ISensor : IDispatch {
#line 245 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(1)] HRESULT  Translation([out,retval] IVector3D **pRetVal);
#line 247 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(2)] HRESULT  Rotation([out,retval] IAngleAxis **pRetVal);
#line 249 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(3)] HRESULT  Device([out,retval] IDispatch **pRetVal);
#line 251 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(4)] HRESULT  Period([out,retval] double *pRetVal);
};

[
	uuid(d6f968e7-2993-48d7-af24-8b602d925b2c),
	dual
] 
#line 268 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface IKeyboard : IDispatch {
#line 274 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(1)] HRESULT  Keys([out,retval] long *pRetVal);
#line 276 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(2)] HRESULT  ProgrammableKeys([out,retval] long *pRetVal);
#line 278 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[id(3)] HRESULT  GetKeyLabel([in] long key, [out,retval] BSTR *pRetVal);
#line 281 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[id(4)] HRESULT  GetKeyName([in] long key, [out,retval] BSTR *pRetVal);
#line 284 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(5)] HRESULT  Device([out,retval] IDispatch **pRetVal);
#line 286 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[id(6)] HRESULT  IsKeyDown([in] long key, [out,retval] VARIANT_BOOL *pRetVal);
#line 289 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[id(1610743814)] HRESULT  IsKeyUp([in] long key, [out,retval] VARIANT_BOOL *pRetVal);
};

[
	uuid(cb3bf65e-0816-482a-bb11-64af1e837812),
	dual
] 
#line 295 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface ISimpleDevice : IDispatch {
#line 301 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[id(1)] HRESULT  Connect();
	[id(2)] HRESULT  Disconnect();
	[propget,id(3)] HRESULT  Sensor([out,retval] ISensor **pRetVal);
#line 305 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(4)] HRESULT  Keyboard([out,retval] IKeyboard **pRetVal);
#line 307 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(5)] HRESULT  Type([out,retval] long *pRetVal);
#line 309 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[propget,id(6)] HRESULT  IsConnected([out,retval] VARIANT_BOOL *pRetVal);
#line 311 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	[id(7)] HRESULT  LoadPreferences([in] BSTR preferencesName);
};

[
	uuid(5f1662ce-ce52-3e87-bed3-ee314df8519d),
	dual
] 
#line 323 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __ISimpleDeviceEvents_DeviceChangeEventHandler : IDispatch {
};

[
	uuid(d7548f4c-9717-3ea3-b843-aa111d017fac),
	dual
] 
#line 327 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __IKeyboardEvents_KeyDownEventHandler : IDispatch {
};

[
	uuid(cb185ef1-0144-3ed4-b0ee-c0c055985f2b),
	dual
] 
#line 331 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __IKeyboardEvents_KeyUpEventHandler : IDispatch {
};

[
	uuid(12fcebc7-8e0e-3e17-a5b3-978cf3371c1c),
	dual
] 
#line 335 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface __ISensorEvents_SensorInputEventHandler : IDispatch {
};

[
	uuid(8a81ecdd-10ec-3082-8302-4673be36ae0f),
	dual
] 
#line 339 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
interface _func : IDispatch {
};


[ version(1.0), uuid(62107833-faa5-371b-aa62-359d8fa53430) ]
library NDOF
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		uuid(8fe3a216-e235-49a6-9136-f9d81fdadef5)
	] 
#line 83 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	dispinterface _ISimpleDeviceEvents {
	properties:

	methods:
#line 90 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
		[id(1)] void  DeviceChange([in] long reserved);
	};

	[
		uuid(6b6bb0a8-4491-40cf-b1a9-c15a801fe151)
	] 
#line 141 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	dispinterface _IKeyboardEvents {
	properties:

	methods:
#line 148 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
		[id(1)] void  KeyDown([in] long keyCode);
#line 150 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
		[id(2)] void  KeyUp([in] long keyCode);
	};

	[
		uuid(e6929a4a-6f41-46c6-9252-a8cc53472cb1)
	] 
#line 188 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
	dispinterface _ISensorEvents {
	properties:

	methods:
#line 195 "i:\\projects\\uni\\05_ws0708\\globefish\\spacenav\\trunk\\spacenav_win32\\3dxndofblender\\release\\tdxinput.tlh"
		[id(1)] void  SensorInput();
	};

	[
		uuid(79E329DD-66A0-3299-A46D-17C76E7BD580),
		version(1.0),
		noncreatable
	] 
	coclass __Impl__ISensorEvents {
		[default] interface IUnknown;
	};

	[
		uuid(DFE48A04-131B-3D9F-8536-BA63D874CB8A),
		version(1.0),
		noncreatable
	] 
	coclass __Impl__IKeyboardEvents {
		[default] interface IUnknown;
	};

}

